spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: auth_service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: data_service
          uri: http://localhost:8082
          predicates:
            - Path=/data/**

